package db

import (
	"context"
	"database/sql"
	"fmt"
)

// Store provides all functions needed to execute DB transactions.
// It extends the Queries struct generated by SQLC to enable the use of transactions.
type Store struct {
	*Queries
	db *sql.DB
}

// NewStore creates a new Store object.
func NewStore(db *sql.DB) *Store {
	return &Store{
		db:      db,
		Queries: New(db),
	}
}

// execTx executes a function within a database transaction.
func (store *Store) execTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := store.db.BeginTx(ctx, nil) // Start a new transaction
	if err != nil {
		return err
	}

	q := New(tx) // Create a new Queries object tied to the transaction

	err = fn(q) // Execute the provided function, passing in the transaction-bound Queries object
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx error: %v, rollback error: %v", err, rbErr)
		}
		return err
	}

	return tx.Commit() // Commit the transaction
}

// TransferTxParams contains all input parameters to transfer money between two accounts.
type TransferTxParams struct {
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	Amount        int64 `json:"amount"`
}

// TransferTxResult is the result of the transfer transaction.
type TransferTxResult struct {
	Transfer    Transfer `json:"transfer"`
	FromAccount Account  `json:"from_account"`
	ToAccount   Account  `json:"to_account"`
	FromEntry   Entry    `json:"from_entry"`
	ToEntry     Entry    `json:"to_entry"`
}

// TransferTx performs a money transfer from one account to another.
// It creates a transfer record, adds account entries, and updates accounts' balances within a database transaction.
func (store *Store) TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error) {
	var result TransferTxResult

	err := store.execTx(ctx, func(q *Queries) error {
		var err error

		// Create the transfer record
		result.Transfer, err = q.CreateTransfer(ctx, CreateTransferParams{
			FromAccountID: arg.FromAccountID,
			ToAccountID:   arg.ToAccountID,
			Amount:        arg.Amount,
		})
		if err != nil {
			return err
		}

		// Add entries for the from account and to account
		result.FromEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.FromAccountID, // Corrected field name
			Amount:    -arg.Amount,       // Negative for debit
		})
		if err != nil {
			return err
		}

		result.ToEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.ToAccountID, // Corrected field name
			Amount:    arg.Amount,      // Positive for credit
		})
		if err != nil {
			return err
		}

		// TODO: Add logic to update the account balances to prevent deadlocks.

		return nil
	})

	return result, err
}
